import { Inter } from 'next/font/google'
import Head from 'next/head'
import NavBar from './component/NavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Furkan | Front-End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='/favicon.ico'></link>
      </Head>
      <NavBar/>
    </div>
  )
}
